### ISSUE TITLE
TypeError: Failed to load plugin '@typescript-eslint' declared in '--config#overrides[0]'

### ISSUE THREAD

**Issue by ezedinff** [eslint-functional/eslint-plugin-functional#377]
I am getting this error when I install this library to my angular project any help please?

```
TypeError: Failed to load plugin '@typescript-eslint' declared in '--config#overrides[0]': Class extends value undefined is not a constructor or null
Referenced from: C:\Users\Dell\WebstormProjects\projects\project1\.eslintrc.json

TypeError: Failed to load plugin '@typescript-eslint' declared in '--config#overrides[0]': Class extends value undefined is not a constructor or null
Referenced from: C:\Users\Dell\WebstormProjects\projects\project1\.eslintrc.json
    at Object.<anonymous> (C:\Users\Dell\WebstormProjects\projects\project1\node_modules\@typescript-eslint\eslint-plugin\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\CLIEngine.js:12:34)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Dell\WebstormProjects\projects\project1\node_modules\@typescript-eslint\eslint-plugin\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\index.js:14:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Process finished with exit code -1
```

**Comment by RebeccaStevens** [comment]
Do you get the error when adding it to a fresh/new angular project?
