### ISSUE TITLE
Crashes on Node 14

### ISSUE THREAD

**Issue by RettentoRectangle** [eslint-functional/eslint-plugin-functional#633]
## Bug Report

It's crashing on Node 14.18.3

Oops! Something went wrong! :(

ESLint: 8.38.0

TypeError: Failed to load plugin 'functional' declared in '.eslintrc.js': values.at is not a function
    at Object.mergeOthers$2 [as mergeOthers] (node_modules\deepmerge-ts\dist\node\index.cjs:202:19)
    at mergeOthers$1 (node_modules\deepmerge-ts\dist\node\index.cjs:368:41)
    at mergeUnknowns (node_modules\deepmerge-ts\dist\node\index.cjs:269:16)
    at Object.mergeRecords$2 [as mergeRecords] (node_modules\deepmerge-ts\dist\node\index.cjs:155:32)
    at mergeRecords$1 (node_modules\deepmerge-ts\dist\node\index.cjs:306:41)
    at mergeUnknowns (node_modules\deepmerge-ts\dist\node\index.cjs:284:20)
    at customizedDeepmerge (node_modules\deepmerge-ts\dist\node\index.cjs:232:16)
    at Object.deepmerge (node_modules\deepmerge-ts\dist\node\index.cjs:222:31)
    at Object.<anonymous> (node_modules\eslint-plugin-functional\lib\index.js:936:33)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)

### Expected behavior

It works on Node 14.

### Actual behavior

It's crashing because deepmerge-ts using Array.prototype.at which is supported from Node 16.6.0

### Steps to reproduce

Try to use this plugin under Node 16.6.0

### Proposed changes

Do not use deepmerge-ts or someone make a PR for that to fix it? :D

**Comment by RebeccaStevens** [comment]
[We require node >=16.10.0](https://github.com/eslint-functional/eslint-plugin-functional/blob/eaa67794ab2c5ad183926a227a944126f4e0ec8b/package.json#L164)
Support for node 14 was dropped with the release of v5.

`deepmerge-ts` isn't the only thing that requires node 16, we have internal code that does too.
Node 14 is quite old now and is about to drop out of LTS so we don't plan on readding support for it.

**Comment by RettentoRectangle** [comment]
Oh, sorry I didn't look at that!
So sad. :|
